/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Shops } from "./Shops";
import { ShopsCountArgs } from "./ShopsCountArgs";
import { ShopsFindManyArgs } from "./ShopsFindManyArgs";
import { ShopsFindUniqueArgs } from "./ShopsFindUniqueArgs";
import { DeleteShopsArgs } from "./DeleteShopsArgs";
import { ShopsService } from "../shops.service";
@graphql.Resolver(() => Shops)
export class ShopsResolverBase {
  constructor(protected readonly service: ShopsService) {}

  async _shopsItemsMeta(
    @graphql.Args() args: ShopsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Shops])
  async shopsItems(@graphql.Args() args: ShopsFindManyArgs): Promise<Shops[]> {
    return this.service.shopsItems(args);
  }

  @graphql.Query(() => Shops, { nullable: true })
  async shops(
    @graphql.Args() args: ShopsFindUniqueArgs
  ): Promise<Shops | null> {
    const result = await this.service.shops(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Shops)
  async deleteShops(
    @graphql.Args() args: DeleteShopsArgs
  ): Promise<Shops | null> {
    try {
      return await this.service.deleteShops(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
