/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FreelancerServices } from "./FreelancerServices";
import { FreelancerServicesCountArgs } from "./FreelancerServicesCountArgs";
import { FreelancerServicesFindManyArgs } from "./FreelancerServicesFindManyArgs";
import { FreelancerServicesFindUniqueArgs } from "./FreelancerServicesFindUniqueArgs";
import { DeleteFreelancerServicesArgs } from "./DeleteFreelancerServicesArgs";
import { FreelancerServicesService } from "../freelancerServices.service";
@graphql.Resolver(() => FreelancerServices)
export class FreelancerServicesResolverBase {
  constructor(protected readonly service: FreelancerServicesService) {}

  async _freelancerServicesItemsMeta(
    @graphql.Args() args: FreelancerServicesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FreelancerServices])
  async freelancerServicesItems(
    @graphql.Args() args: FreelancerServicesFindManyArgs
  ): Promise<FreelancerServices[]> {
    return this.service.freelancerServicesItems(args);
  }

  @graphql.Query(() => FreelancerServices, { nullable: true })
  async freelancerServices(
    @graphql.Args() args: FreelancerServicesFindUniqueArgs
  ): Promise<FreelancerServices | null> {
    const result = await this.service.freelancerServices(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FreelancerServices)
  async deleteFreelancerServices(
    @graphql.Args() args: DeleteFreelancerServicesArgs
  ): Promise<FreelancerServices | null> {
    try {
      return await this.service.deleteFreelancerServices(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
