/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Goods } from "./Goods";
import { GoodsCountArgs } from "./GoodsCountArgs";
import { GoodsFindManyArgs } from "./GoodsFindManyArgs";
import { GoodsFindUniqueArgs } from "./GoodsFindUniqueArgs";
import { DeleteGoodsArgs } from "./DeleteGoodsArgs";
import { GoodsService } from "../goods.service";
@graphql.Resolver(() => Goods)
export class GoodsResolverBase {
  constructor(protected readonly service: GoodsService) {}

  async _goodsItemsMeta(
    @graphql.Args() args: GoodsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Goods])
  async goodsItems(@graphql.Args() args: GoodsFindManyArgs): Promise<Goods[]> {
    return this.service.goodsItems(args);
  }

  @graphql.Query(() => Goods, { nullable: true })
  async goods(
    @graphql.Args() args: GoodsFindUniqueArgs
  ): Promise<Goods | null> {
    const result = await this.service.goods(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Goods)
  async deleteGoods(
    @graphql.Args() args: DeleteGoodsArgs
  ): Promise<Goods | null> {
    try {
      return await this.service.deleteGoods(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
