/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { JobOpportunities } from "./JobOpportunities";
import { JobOpportunitiesCountArgs } from "./JobOpportunitiesCountArgs";
import { JobOpportunitiesFindManyArgs } from "./JobOpportunitiesFindManyArgs";
import { JobOpportunitiesFindUniqueArgs } from "./JobOpportunitiesFindUniqueArgs";
import { DeleteJobOpportunitiesArgs } from "./DeleteJobOpportunitiesArgs";
import { JobOpportunitiesService } from "../jobOpportunities.service";
@graphql.Resolver(() => JobOpportunities)
export class JobOpportunitiesResolverBase {
  constructor(protected readonly service: JobOpportunitiesService) {}

  async _jobOpportunitiesItemsMeta(
    @graphql.Args() args: JobOpportunitiesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [JobOpportunities])
  async jobOpportunitiesItems(
    @graphql.Args() args: JobOpportunitiesFindManyArgs
  ): Promise<JobOpportunities[]> {
    return this.service.jobOpportunitiesItems(args);
  }

  @graphql.Query(() => JobOpportunities, { nullable: true })
  async jobOpportunities(
    @graphql.Args() args: JobOpportunitiesFindUniqueArgs
  ): Promise<JobOpportunities | null> {
    const result = await this.service.jobOpportunities(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => JobOpportunities)
  async deleteJobOpportunities(
    @graphql.Args() args: DeleteJobOpportunitiesArgs
  ): Promise<JobOpportunities | null> {
    try {
      return await this.service.deleteJobOpportunities(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
